version: '3.8'

services:
  mocks:
    image: wiremock/wiremock:3.8.0
    restart: always
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/__admin/mappings" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./mocks/${MOCKS_DIRECTORY:-docker}/mappings:/home/wiremock/mappings
#      - .mocks/__files:/home/wiremock/__files

  app:
    build: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mocks:
        condition: service_healthy
    environment:
      - EUREKA_URL=http://mocks:8080
      - KEYCLOAK_URL=http://mocks:8080
    healthcheck:
      test: "curl --fail --silent http://localhost:8080/private/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
